### ISSUE TITLE
Modeling the data

### ISSUE THREAD

**Issue by reginafcompton** [datamade/committee-oversight#1]
@beamalsky and I looked at the spreadsheets from the Lugar center and identified some data models. Most align nicely with the Open Civic Data standard. For reference, I am sharing relevant links to those.

OCD Event::Hearing
[Model](https://github.com/opencivicdata/python-opencivicdata/blob/master/opencivicdata/legislative/models/event.py#L48)

OCD EventDocument::Report (see "Hearing/Report" column in spreadsheet)
[python-opencivicdata model](https://github.com/opencivicdata/python-opencivicdata/blob/master/opencivicdata/legislative/models/event.py#L97)

OCD Organization::Committee and Subcommittee
[python-opencivicdata model](https://github.com/opencivicdata/python-opencivicdata/blob/master/opencivicdata/core/models/people_orgs.py#L83), but might be easier to read the [Pupa schema](https://github.com/opencivicdata/pupa/blob/master/pupa/scrape/schemas/organization.py)

OCD Person::Person (see the individuals listed as "Chair" at the top of the spreadsheet)
[python-opencivicdata](https://github.com/opencivicdata/python-opencivicdata/blob/master/opencivicdata/core/models/people_orgs.py#L348), plus the [pupa schema](https://github.com/opencivicdata/pupa/blob/master/pupa/scrape/schemas/person.py)

OCD Membership::How the person/chair relates to a committee
[python-opencivicdata](https://github.com/opencivicdata/python-opencivicdata/blob/master/opencivicdata/core/models/people_orgs.py#L498)

**Comment by reginafcompton** [comment]
We will continue to build this out, after taking a look at the scraped data.

**Comment by beamalsky** [comment]
After looking at the scraped data, we're going to use the OCD models in full!
