### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by beamalsky** [datamade/committee-oversight#10]
Lugar Center staff should be able to create accounts, log in, and save entries

**Comment by beamalsky** [comment]
https://docs.djangoproject.com/en/2.1/topics/auth/

**Comment by beamalsky** [comment]
Useful link: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Authentication

Question: Do users need to be able to reset their passwords?

**Comment by fgregg** [comment]
For this application, I think it will be fine if super users (i.e.
DataMade) can reset user passwords.

**Comment by beamalsky** [comment]
👍🏻
