### ISSUE TITLE
Crontasks don't seem to be working on production

### ISSUE THREAD

**Issue by beamalsky** [datamade/committee-oversight#166]
Why?

They're in the place I'd expect:

```bash
Beas-MBP:committee-oversight beamalsky$ ssh ubuntu@committeeoversight-production.datamade.us

ubuntu@ip-10-0-0-175:~$ cat /etc/cron.d/committee-oversight-crontasks
# /etc/cron.d/committee-oversight-crontasks

# Back up the hearings database at 4 AM GMT (11pm EST) every day.
0 4 * * * datamade (pg_dump -Fc -U postgres -d hearings | /usr/bin/aws s3 cp - s3://datamade-postgresql-backups/hearings/$(date -d "today" +"\%Y\%m\%d\%H\%M").dump) && echo "staging backup $(date -d "today" +"\%Y\%m\%d\%H\%M").dump complete" >> /tmp/committee-oversight-crontasks.log 2>&1

# Update the Committee Ratings table every hour.
0 * * * * datamade cd /home/datamade/committee-oversight-d-FBYTDKXO2 && /home/datamade/.virtualenvs/committee-oversight-d-FBYTDKXO2/bin/python manage.py load_committeeratings >> /tmp/committee-oversight-crontasks.log 2>&1
```

But they haven't run since I did it manually on 2/21:

```
mp/committee-oversight-crontasks.log 2>&1ubuntu@ip-10-0-0-175:~$ tail /tmp/committee-oversight-crontasks.log
Added rating counts for 116th Congress to Senate Committee on Health, Education, Labor, and Pensions. Total points = 23.
Added rating counts for 116th Congress to Senate Committee on Homeland Security and Governmental Affairs. Total points = 15.
Added rating counts for 116th Congress to Senate Committee on Indian Affairs. Total points = 9.
Added rating counts for 116th Congress to Senate Committee on Intelligence. Total points = 14.
Added rating counts for 116th Congress to Senate Committee on Judiciary. Total points = 27.
Added rating counts for 116th Congress to Senate Committee on Rules and Administration. Total points = 2.
Added rating counts for 116th Congress to Senate Committee on Small Business and Entrepreneurship. Total points = 18.
Added rating counts for 116th Congress to Senate Committee on Veterans' Affairs. Total points = 12.
2020-02-21 09:34:05.257494: Committee rating update completed!
staging backup \2020\02\21\16\38.dump complete
```

**Comment by beamalsky** [comment]
Still not working, reopening

**Comment by fgregg** [comment]
i'd be suspicious of 

cd /home/datamade/committee-oversight-**d-FBYTDKXO2**

looks tied to specific deployment

**Comment by beamalsky** [comment]
For posterity: the deployment ID is added [here](https://github.com/datamade/committee-oversight/blob/master/scripts/render_configs.py), and it turns out Jinja strips new lines spaces at the end of files so @hancush added it back in manually (see her comment in the file). Thank you Hannah!!

**Comment by beamalsky** [comment]
The S3 bucket with the db backups has a new one every day but they seem to have the data from the staging site. That's not what we want! Eg, when I download this one: https://s3.console.aws.amazon.com/s3/object/datamade-postgresql-backups/hearings/202004230400.dump?region=us-east-1&tab=overview

and run 

```
docker-compose -f docker-compose.yml -f docker-compose.db-ops.yml run -e PGPASSWORD=postgres --rm dbload-dump
docker-compose up
```

I see this: 
<img width="1388" alt="Screen Shot 2020-04-23 at 11 10 05 AM" src="https://user-images.githubusercontent.com/1094243/80122335-058b0c80-8553-11ea-974e-4c0f993d385b.png">

**Comment by beamalsky** [comment]
I noticed that I was still creating my crontask on staging in the `render_config.py` file, so I added a conditional to prevent that [here](https://github.com/datamade/committee-oversight/pull/183/commits/7a1cbe308d2f5072b0bd840b49b6d7853030f377). I'm also finding it difficult to sort through the committee ratings script log messages to find the backup messages, so I split them out into separate log files [here](https://github.com/datamade/committee-oversight/pull/183/commits/f23c8032755eeeffaf186eec994049d8a8f6844b).

I've also gone in and manually created a new backup from the production site, which now lives [here](https://s3.console.aws.amazon.com/s3/object/datamade-postgresql-backups/hearings/%255C2020%255C04%255C23%255C16%255C30.dump?region=us-east-1). 

I'm going to confirm the latter worked, manually deploy to production, and then check back tomorrow to see if this fixes the issue.

**Comment by beamalsky** [comment]
Update: I checked the backup from last night and it looks like this :( 
<img width="694" alt="Screen Shot 2020-04-27 at 3 29 45 PM" src="https://user-images.githubusercontent.com/1094243/80417827-0649d880-889c-11ea-8505-aee5c2e3567f.png">

**Comment by beamalsky** [comment]
I ssh-ed into the production server, looked `/etc/cron.d/committee-oversight-crontasks`, and ran the following from it to make a manual backup: 

```
datamade@ip-10-0-0-175:/etc/cron.d$ (pg_dump -Fc -U postgres -d hearings | /usr/bin/aws s3 cp - s3://datamade-postgresql-backups/hearings/$(date -d "today" +"\%Y\%m\%d\%H\%M").dump) && echo "backup $(date -d "today" +"\%Y\%m\%d\%H\%M").dump complete"
backup \2020\04\27\20\33.dump complete
```

Here are the crontask logs: 

```
datamade@ip-10-0-0-175:/etc/cron.d$ tail /tmp/committee-oversight-crontasks-backups.log
backup 202004240402.dump complete
backup 202004250402.dump complete
backup 202004260402.dump complete
backup 202004270402.dump complete
```

```
datamade@ip-10-0-0-175:/etc/cron.d$ tail /tmp/committee-oversight-crontasks-ratings.log
Added rating counts for 116th Congress to Senate Committee on Foreign Relations. Total points = 124.
Added rating counts for 116th Congress to Senate Committee on Health, Education, Labor, and Pensions. Total points = 36.
Added rating counts for 116th Congress to Senate Committee on Homeland Security and Governmental Affairs. Total points = 103.
Added rating counts for 116th Congress to Senate Committee on Indian Affairs. Total points = 47.
Added rating counts for 116th Congress to Senate Committee on Intelligence. Total points = 193.
Added rating counts for 116th Congress to Senate Committee on Judiciary. Total points = 143.
Added rating counts for 116th Congress to Senate Committee on Rules and Administration. Total points = 17.
Added rating counts for 116th Congress to Senate Committee on Small Business and Entrepreneurship. Total points = 51.
Added rating counts for 116th Congress to Senate Committee on Veterans' Affairs. Total points = 47.
2020-04-27 15:00:29.590190: Committee rating update completed!
```

**Comment by beamalsky** [comment]
The manual backup ([here](https://s3.console.aws.amazon.com/s3/object/datamade-postgresql-backups/hearings/%255C2020%255C04%255C27%255C20%255C31.dump?region=us-east-1&tab=overview)) matches the production site: 

<img width="694" alt="Screen Shot 2020-04-27 at 3 44 14 PM" src="https://user-images.githubusercontent.com/1094243/80419034-f92de900-889d-11ea-94e1-166509b399b2.png">

**Comment by beamalsky** [comment]
The backups (eg, the one from [last night](https://s3.console.aws.amazon.com/s3/object/datamade-postgresql-backups/hearings/202004280400.dump?region=us-east-1&tab=overview)) now work. I'm going to check on this again next time I pick up this project. If they're still working, I'll close it.

**Comment by beamalsky** [comment]
The [backup from last night](https://s3.console.aws.amazon.com/s3/object/datamade-postgresql-backups/hearings/202005120400.dump?region=us-east-1&tab=overview) looks good. I'm going to call this issue closed.
