### ISSUE TITLE
Rebuild migrations

### ISSUE THREAD

**Issue by reginafcompton** [datamade/committee-oversight#19]
Currently, the app has a minor migration snafu. Here's what's going on.
- the app requires a particular branch of [python-opencivicdata](https://github.com/datamade/committee-oversight/blob/master/requirements.txt#L7), i.e., `longer_event_names`

- the `longer_event_names` branch [does not have a migration (which adds an `extras` field)](https://github.com/opencivicdata/python-opencivicdata/tree/longer_event_names/opencivicdata/legislative/migrations) for the VoteEvent. Why?
    - somehow, [this recent commit](https://github.com/opencivicdata/python-opencivicdata/commit/8d12bf9494d318068b32e2c310d3917c35635b6e) omits the migration
    - the [master branch remedies the problem](https://github.com/opencivicdata/python-opencivicdata/commit/3fcbae298b95311b1d9b02faf9a86704f1632234), but that solution came after the branching of `longer_event_names` 

@fgregg - it seems like this could be solved by having you run `make migrations` on your branch of `opencivicdata` or by merging your branch with master. Does that make sense?

Then, Bea can rebuild the migrations for `committee-oversight`.

**Comment by beamalsky** [comment]
@fgregg I reinstalled OCD with your updated branch, but now when I try to migrate I get this error:
```
CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0007_auto_20181029_1527, 0007_longer_event_name in legislative).
To fix them run 'python manage.py makemigrations --merge'
```

@reginafcompton and I think is because both migrations referenced above point to the same dependency. Could you choose one or update the dependency?
