### ISSUE TITLE
Matching approach

### ISSUE THREAD

**Issue by fgregg** [datamade/committee-oversight#45]
1. For senate hearings, try to match on serial number
2. For house meetings, try to match on name of committee / subcommittee and date time.

**Comment by beamalsky** [comment]
Four-hour authorization description from Forest: 

> My understanding is that these hours are for implementing a matching approach in in the script that imports Lugar's data into the database that we expect will be significantly better than matching on the title of the hearing. This is with the understanding that while the matching will be better, it will not be perfect.

**Comment by beamalsky** [comment]
Caveat: Not all senate hearings in the scraped data or manually entered data have serial numbers. If that's missing on either end, I'm thinking I should then try to match on name of committee / subcommittee and date time. Does that make sense to you @fgregg?

**Comment by fgregg** [comment]
Yep!

**Comment by beamalsky** [comment]
@fgregg can this be closed?

**Comment by fgregg** [comment]
yes
