### ISSUE TITLE
Setting up the form fields

### ISSUE THREAD

**Issue by beamalsky** [datamade/committee-oversight#7]
Fields the forms should have:
- Hearing Title (`opencivicdata_event`)
- Date (`opencivicdata_event`)
- Classification (`opencivicdata_event`)
- Committee/subcommittee (`opencivicdata_eventparticipant`; multiple select)
- Committee members present (`opencivicdata_eventparticipant`; multiple select)
- Witnesses (`opencivicdata_eventparticipant`; multiple select)
- Link to transcript (`opencivicdata_eventdocument` and `opencivicdata_eventdocumentlink`)

**Comment by beamalsky** [comment]
Other fields to fill in when submitted:

`opencivicdata_event`
- created_at
- updated_at
- id (create)
- all_day = false
- status = confirmed
- jurisdiction_id ?
- location_id ?

`opencivicdata_eventparticipant`
- id (create)
- entity_type
- note
- event_id
- organization_id (if a committee or subcommittee)

`opencivicdata_eventdocument` 
- TBD

`opencivicdata_eventdocumentlink` 
- TBD

**Comment by beamalsky** [comment]
Open questions:

1. At the moment, `Committee/subcommittee` is a messy list from the scraped data. Do we want to clean that?
2. Do we want to let the data enterer create a new `Committee/subcommittee` on the fly?
3. Do we want live filtering by committee to find subcommittees? Right now it's one big list
4. Is `classifications` a set list, or should users be able to update?
5. How should we make transcript archive urls? SFM monitor has a method.
6. Transcript type is put in manually now. Should we determine that automatically from the url?

**Comment by fgregg** [comment]
1. It will get better.
2. No
3. what dose live filtering mean?
4. I don't know?
5. use the SFM method
6. if possible, otherwise don't set it.

**Comment by beamalsky** [comment]
@fgregg For 3: Should the user to be able to select a committee and then see a list of its subcommittees? If not we should make sure either 1) all subcommittee names are unique or 2) subcommittees contain a reference to their committee

**Comment by fgregg** [comment]
All subcommittee names are *not* unique. 

A hierarchical dropdown makes sense to me.

**Comment by beamalsky** [comment]
Thanks! Closing this and breaking into smaller issues.
