### ISSUE TITLE
Update navbar to handle admin login and dynamic updating

### ISSUE THREAD

**Issue by beamalsky** [datamade/committee-oversight#76]
The site navbar should update dynamically based on which pages are set as visible in the Wagtail backend. Here's a how-to for that: https://www.tivix.com/blog/working-with-wagtail-menus

Here's how I ended up doing it for LISC: https://github.com/datamade/lisc-cnda/pull/63

In addition, we'll always want `Home` and `Login` nav items. Logged in users should see an `Admin` option in the navbar where they can create, edit, and delete hearings (the current menu items at https://committeeoversight.datamade.us/; work done in Phase 1 of this project)

**Comment by hancush** [comment]
@beamalsky – Ready for re-view! I left login/logout as top-level nav items, but applied your style change and moved the admin actions into a dropdown.
<img width="1552" alt="Screen Shot 2019-09-24 at 10 47 56 AM" src="https://user-images.githubusercontent.com/12176173/65527766-d3c89f00-deb8-11e9-9d27-3bf847322a47.png">
<img width="1552" alt="Screen Shot 2019-09-24 at 10 48 08 AM" src="https://user-images.githubusercontent.com/12176173/65527768-d3c89f00-deb8-11e9-9a63-4b464ad5faf4.png">
<img width="1552" alt="Screen Shot 2019-09-24 at 10 48 12 AM" src="https://user-images.githubusercontent.com/12176173/65527769-d4613580-deb8-11e9-906f-d60899d3773e.png">

**Comment by beamalsky** [comment]
Closed by #84
