### ISSUE TITLE
Archive URLs

### ISSUE THREAD

**Issue by beamalsky** [datamade/committee-oversight#9]
@evz could you help me understand how SFM archives URLS? Here's what I'm looking at from SFM:

```python
def archive_source_url(source):

    if source.source_url:
        wayback_host = 'http://web.archive.org'
        save_url = '{0}/save/{1}'.format(wayback_host, source.source_url)
        archived = requests.get(save_url)
        source.archive_url = '{0}{1}'.format(wayback_host,
                                             archived.headers['Content-Location'])
        source.save()

```
And here's a pared down version that I currently have in this Lugar app: 

```python
def archive_url(url):
    wayback_host = 'http://web.archive.org'
    save_url = '{0}/save/{1}'.format(wayback_host, url)
    archive_url = '{0}{1}'.format(wayback_host, save_url)
    return archive_url
```

I'm not sure what I lost by cutting that `request.get`

**Comment by fgregg** [comment]
the requests.get is actually what tells the internet archive to archive it. without it you are not communicating with the archive.

**Comment by beamalsky** [comment]
Ah gotcha. Do you think it makes sense to save archived urls with the same `media_type` as their unarchived counterpart?

**Comment by fgregg** [comment]
yes.
